<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\ReveilMusical.Infrastructure\ReveilMusical.Infrastructure.csproj" />
    <ProjectReference Include="..\ReveilMusical.TestSupport\ReveilMusical.TestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

</Project>
